# Assignment Day 3

## Question 1:

### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
# Importing Numpy with alias name
import numpy as np

# Creating an array using Numpy arange
arr = np.arange(2, 50, 3)

# Printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question 2:

### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
# Importing Numpy with alias name
import numpy as np

# Creating 2 empty lists:
lst_1 = []
lst_2 = []

# Getting values for list_1 from user:
for i in range(5):
    x=int(input())
    lst_1.append(x)

# Getting values for list_2 from user:
for i in range(5):
    x=int(input())
    lst_2.append(x)

# Converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# Concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print(arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print(sortArr)

1
2
6
3
8
5
9
7
10
4
[ 1  2  6  3  8  5  9  7 10  4]
[ 1  2  3  4  5  6  7  8  9 10]


## Question 3:

### Write a code snippet to find the dimensions of a ndarray and its size.

In [7]:
# importing Numpy
import numpy as np

# Creating a 2d array
arr = np.array([[1,2,3],[4,5,6]])

# Printing array dimensions (axes)
print(arr.ndim)
 
# Printing size of array
print(arr.size)

2
6


## Question 4:

### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [19]:
# importing numpy
import numpy as np
x = np.array([1, 2])

#ArrayName[numpy.newaxis, :]               - row major
#ArrayName[:, numpy.newaxis]               - column major
#numpy.expand_dims(ArrayName, axis = 0)    -  row major
#numpy.expand_dims(ArrayName, axis = 1)    -  column major

m = arr[np.newaxis, :]
n = arr[:, np.newaxis]
p = np.expand_dims(x, axis=0)
q = np.expand_dims(x, axis=1)
r = np.expand_dims(x, axis=(0, 1))
s = np.expand_dims(x, axis=(2, 0))
print('\n',m) # converting using newaxis in row wise
print('\n',n) # converting using newaxis in column wise
print('\n',p) # converting using newaxis in row wise
print('\n',q) # converting using newaxis in column wise
print('\n',r)
print('\n',s)


 [[1 2 3 4 5 6]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

 [[1 2]]

 [[1]
 [2]]

 [[[1 2]]]

 [[[1]
  [2]]]


## Question 5:

### Consider two square numpy arrays. Stack them vertically and horizontally.

In [23]:
# importing numpy
import numpy as np

# creating 2 arrays with square values
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print(np.hstack((arr_1, arr_2))) # Horitzontal Stack
print(np.vstack((arr_1, arr_2))) # Vertical Stack

[  1   4   9  16  25  36  49  64  81 100]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


## Question 6:

### How to get unique items and counts of unique items?

In [26]:
# importing numpy
import numpy as np

# creating an array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

print(unique,counts)

[ 1  2  3  4  5  6  7  8  9 10 16 25] [2 2 1 2 2 1 1 1 1 1 1 1]
